# Generated by Django 2.2.5 on 2019-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('key_word', models.CharField(max_length=20)),
                ('count_word', models.PositiveIntegerField(verbose_name='Количество')),
                ('datestamp', models.DateTimeField(verbose_name='Задача обновлена')),
                ('date_create', models.DateTimeField(verbose_name='Задача отправлена')),
                ('status', models.IntegerField(choices=[(0, 'отправлено, результата не знаю'), (1, 'выполнено')], default=0, verbose_name='Статус')),
            ],
        ),
    ]
