# Generated by Django 2.2.5 on 2019-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlitem',
            options={'ordering': ('-date_create',)},
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Задача отправлена'),
        ),
        migrations.AlterField(
            model_name='urlitem',
            name='datestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Задача обновлена'),
        ),
    ]
