# Generated by Django 2.2.5 on 2019-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20190918_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='count_word',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
