# Generated by Django 2.2.5 on 2019-09-19 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_auto_20190919_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
